function [fitresult, gof] = createFit(timecut, cutsig)
%CREATEFIT(TIMECUT,CUTSIG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : timecut
%      Y Output: cutsig
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Dec-2016 13:01:59


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( timecut, cutsig );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
%opts.Display = 'On';
% opts.StartPoint = [29.0877472783641 -1.01422807359693];
% opts.Upper = [1000,1000];
% opts.Lower = [0.0001,0.0001];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y
% grid on


